rm *.aux *.synctex.gz *.log *.snm *.out *.bbl

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

rm -f .git/index.lock

Use git pull to fetch and merge changes from origin master to local branch

git pull

Then solve the confiction in merge (if exist) - by editing directly in the file. Finally add the file back

git add .

Commit as usual

git commit --all -m "Resolved the conficliction"

Notice that the pull command should be done first, because it will not automatically add new folder to local branch.


A cuong dep giai
